name: Static Site CI
on:
  schedule:
    - cron: "0 1 * * *"      # раз в сутки
  repository_dispatch:
    types: [static_site]
  workflow_dispatch:
jobs:
  release:
    name: Build and deploy site
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.GH_PAT }}
      - uses: upptime/uptime-monitor@master
        with:
          command: "site"
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
